// Code generated by goyacc -l -o gram.go gram.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"strings"

	"github.com/indexdata/ccms/cmd/ccd/ast"
)

type yySymType struct {
	yys      int
	node     ast.Node
	str      string
	nodeList []ast.Node
}

const GT_OR_EQUAL = 57346
const LT_OR_EQUAL = 57347
const NOT_EQUAL = 57348
const ADD = 57349
const ALL = 57350
const ALTER = 57351
const AND = 57352
const ARCHIVE = 57353
const ARCHIVED = 57354
const ASC = 57355
const BY = 57356
const CASCADE = 57357
const CREATE = 57358
const COUNT = 57359
const DELETE = 57360
const DESC = 57361
const DROP = 57362
const ENCRYPTED = 57363
const FILTER = 57364
const FROM = 57365
const FUND = 57366
const ILIKE = 57367
const IN = 57368
const INFO = 57369
const INSERT = 57370
const INTO = 57371
const LIKE = 57372
const LIMIT = 57373
const NOT = 57374
const NULL = 57375
const OFFSET = 57376
const OR = 57377
const ORDER = 57378
const PASSWORD = 57379
const PROJECT = 57380
const PROJECTS = 57381
const PROPERTY = 57382
const PING = 57383
const RETRIEVE = 57384
const SELECT = 57385
const SET = 57386
const SHOW = 57387
const TAG = 57388
const TO = 57389
const UPDATE = 57390
const USER = 57391
const VERSION = 57392
const WHERE = 57393
const WITH = 57394
const IDENT = 57395
const NUMBER = 57396
const SLITERAL = 57397

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"GT_OR_EQUAL",
	"LT_OR_EQUAL",
	"NOT_EQUAL",
	"ADD",
	"ALL",
	"ALTER",
	"AND",
	"ARCHIVE",
	"ARCHIVED",
	"ASC",
	"BY",
	"CASCADE",
	"CREATE",
	"COUNT",
	"DELETE",
	"DESC",
	"DROP",
	"ENCRYPTED",
	"FILTER",
	"FROM",
	"FUND",
	"ILIKE",
	"IN",
	"INFO",
	"INSERT",
	"INTO",
	"LIKE",
	"LIMIT",
	"NOT",
	"NULL",
	"OFFSET",
	"OR",
	"ORDER",
	"PASSWORD",
	"PROJECT",
	"PROJECTS",
	"PROPERTY",
	"PING",
	"RETRIEVE",
	"SELECT",
	"SET",
	"SHOW",
	"TAG",
	"TO",
	"UPDATE",
	"USER",
	"VERSION",
	"WHERE",
	"WITH",
	"IDENT",
	"NUMBER",
	"SLITERAL",
	"';'",
	"'*'",
	"'('",
	"')'",
	"'='",
	"'<'",
	"'>'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 223

var yyAct = [...]uint8{
	114, 166, 109, 105, 103, 89, 110, 106, 79, 138,
	137, 185, 120, 202, 201, 186, 200, 199, 125, 124,
	184, 168, 122, 96, 140, 139, 82, 81, 97, 56,
	57, 36, 180, 54, 58, 63, 169, 50, 65, 66,
	67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
	77, 206, 78, 112, 57, 115, 178, 205, 204, 133,
	84, 85, 53, 108, 203, 57, 135, 136, 196, 55,
	189, 149, 183, 112, 147, 115, 57, 113, 132, 92,
	91, 95, 100, 131, 57, 117, 116, 99, 176, 118,
	175, 57, 150, 59, 57, 174, 173, 113, 90, 123,
	86, 121, 126, 127, 57, 117, 116, 60, 61, 118,
	94, 57, 102, 130, 101, 98, 134, 57, 152, 62,
	39, 142, 57, 141, 37, 146, 148, 145, 4, 143,
	128, 153, 154, 156, 157, 158, 159, 155, 38, 188,
	164, 167, 160, 161, 162, 163, 171, 51, 83, 80,
	45, 177, 179, 181, 182, 151, 119, 197, 93, 172,
	25, 88, 26, 198, 40, 64, 41, 27, 46, 28,
	47, 29, 129, 190, 191, 192, 193, 194, 30, 31,
	42, 87, 1, 165, 48, 111, 43, 167, 195, 107,
	49, 44, 35, 104, 32, 187, 33, 170, 144, 34,
	52, 23, 22, 21, 20, 24, 19, 18, 17, 16,
	15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
	3, 5, 2,
}

var yyPact = [...]int16{
	151, -1000, -1000, -25, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 100, 82, 142, 127, 146,
	-18, 118, 12, 69, 23, -1000, 151, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	-1000, 23, 126, -31, -1000, -1000, -32, -1000, 122, 23,
	23, -1000, -1000, 56, -1000, 172, 152, -1000, 47, -1000,
	-1000, -1000, 28, 47, -1000, -1000, 143, -1000, 67, -1000,
	23, -36, -29, 77, -1000, -1000, 58, 74, 72, -1000,
	31, 135, -1000, -1000, -45, 47, -1000, -37, 23, -41,
	-42, 23, 23, -1000, 95, 162, -1000, 53, 31, 5,
	-1000, -1000, -33, -34, -1000, -1000, -1000, -1000, 31, 84,
	126, 91, -1000, -1000, 41, 38, 48, 111, 31, 31,
	51, 51, 51, 51, -1000, 51, 51, 51, 51, 23,
	23, -38, -19, -1000, 115, 145, 45, 44, 39, 37,
	1, -23, 23, 64, 162, -1000, 5, 5, 5, 5,
	-1000, -1000, -1000, -1000, -39, -48, -1000, -1000, -1000, -1000,
	105, 16, 23, 23, 23, 23, 23, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 23, -1000, 14, -1000,
	144, -43, -44, -46, -47, -1000, -1000, -1000, -1000, 10,
	4, 3, -3, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 222, 221, 128, 220, 219, 218, 217, 216, 215,
	214, 213, 212, 211, 210, 209, 208, 207, 206, 205,
	204, 203, 202, 201, 200, 8, 5, 198, 197, 195,
	4, 193, 3, 189, 2, 7, 6, 185, 183, 1,
	0, 182,
}

var yyR1 = [...]int8{
	0, 41, 1, 4, 4, 4, 3, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 7, 5, 5, 6,
	6, 6, 6, 6, 8, 9, 10, 11, 12, 13,
	14, 15, 16, 16, 17, 18, 18, 20, 19, 21,
	21, 22, 22, 22, 22, 22, 22, 23, 23, 23,
	23, 24, 24, 24, 25, 26, 26, 27, 27, 27,
	27, 28, 28, 29, 29, 30, 31, 31, 32, 32,
	35, 35, 33, 33, 33, 33, 33, 34, 34, 34,
	34, 34, 36, 36, 36, 37, 37, 37, 37, 37,
	38, 38, 39, 40,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 2, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 3, 8, 8, 8,
	8, 8, 8, 8, 4, 3, 3, 3, 7, 4,
	3, 3, 3, 4, 3, 1, 2, 6, 1, 3,
	4, 2, 5, 3, 3, 2, 2, 10, 10, 10,
	10, 1, 1, 4, 6, 2, 0, 3, 4, 4,
	0, 2, 0, 2, 0, 1, 1, 3, 1, 3,
	1, 2, 1, 3, 3, 3, 3, 1, 3, 3,
	3, 3, 1, 4, 4, 1, 1, 1, 1, 3,
	1, 3, 1, 1,
}

var yyChk = [...]int16{
	-1000, -41, -1, -4, -3, -2, -5, -6, -7, -8,
	-9, -10, -11, -12, -13, -14, -15, -16, -17, -18,
	-20, -21, -22, -23, -19, 9, 11, 16, 18, 20,
	27, 28, 43, 45, 48, 41, 56, 24, 38, 38,
	22, 24, 38, 44, 49, 23, 22, 24, 38, 44,
	55, 29, -24, 50, -40, 57, 17, 53, -40, 24,
	38, 39, 50, -40, -3, -40, -40, -40, -40, -40,
	-40, -40, -40, -40, -40, -40, -40, -40, -40, -25,
	23, 58, 58, 26, -40, -40, 44, 9, 9, -26,
	51, 52, -26, 15, 43, -40, 59, 57, 38, -40,
	24, 40, 40, -30, -31, -32, -35, -33, 32, -34,
	-36, -37, 22, 46, -40, 24, 55, 54, 58, 21,
	57, -26, 59, -40, 60, 60, -40, -40, 35, 10,
	60, 30, 25, 6, -35, 61, 62, 5, 4, 58,
	58, -30, 37, -25, -27, 36, -40, 33, -40, 33,
	44, 44, 7, 20, -32, -35, -34, -34, -34, -34,
	-36, -36, -36, -36, -40, -38, -39, -40, 59, 55,
	-28, 31, 14, 51, 51, 51, 51, -40, 55, -40,
	55, -40, -40, 8, 59, 59, 63, -29, 34, 54,
	-40, -40, -40, -40, -40, -39, 54, 13, 19, 60,
	60, 60, 60, 54, 54, 54, 54,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 22, 23, 24, 25, 0, 0, 0, 0, 0,
	45, 0, 0, 0, 0, 48, 4, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	46, 0, 0, 0, 61, 62, 0, 103, 51, 0,
	0, 55, 56, 0, 5, 0, 0, 26, 66, 35,
	36, 37, 0, 66, 40, 41, 42, 44, 0, 49,
	0, 0, 0, 0, 53, 54, 0, 0, 0, 34,
	0, 0, 39, 43, 0, 66, 50, 0, 0, 0,
	0, 0, 0, 65, 75, 76, 78, 80, 0, 82,
	87, 92, 0, 0, 95, 96, 97, 98, 0, 0,
	0, 70, 63, 52, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 81, 0, 0, 0, 0, 0,
	0, 0, 0, 47, 72, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 77, 79, 83, 84, 85, 86,
	88, 89, 90, 91, 0, 0, 100, 102, 99, 38,
	74, 0, 0, 0, 0, 0, 0, 27, 28, 29,
	30, 31, 32, 33, 93, 94, 0, 64, 0, 71,
	67, 0, 0, 0, 0, 101, 73, 68, 69, 0,
	0, 0, 0, 57, 58, 59, 60,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	58, 59, 57, 3, 63, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 56,
	61, 60, 62,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.ParseTree{Commands: yyDollar[1].nodeList}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].nodeList...)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{yyDollar[1].node}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ArchiveProjectStmt{}
		}
	case 27:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterFundStmt{Fund: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: yyDollar[8].str, StringLiteral: false}
		}
	case 28:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterFundStmt{Fund: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: ast.DecodeSLiteral(yyDollar[8].str), StringLiteral: true}
		}
	case 29:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: yyDollar[8].str, StringLiteral: false}
		}
	case 30:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: ast.DecodeSLiteral(yyDollar[8].str), StringLiteral: true}
		}
	case 31:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Add, Value: yyDollar[8].str}
		}
	case 32:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Drop, Value: yyDollar[8].str}
		}
	case 33:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Drop, Value: "*"}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CreateFilterStmt{Filter: yyDollar[3].str, Where: yyDollar[4].node}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateFundStmt{Fund: yyDollar[3].str}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateProjectStmt{Project: yyDollar[3].str}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateSetStmt{Set: yyDollar[3].str}
		}
	case 38:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.CreateUserStmt{User: yyDollar[3].str, EncryptedPassword: ast.DecodeSLiteral(yyDollar[7].str)}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DeleteStmt{From: yyDollar[3].str, Where: yyDollar[4].node}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropFilterStmt{Filter: yyDollar[3].str}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropFundStmt{Fund: yyDollar[3].str}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropProjectStmt{Project: yyDollar[3].str}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DropProjectStmt{Project: yyDollar[3].str, Cascade: true}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropSetStmt{Set: yyDollar[3].str}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: ""}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: ast.DecodeSLiteral(yyDollar[2].str)}
		}
	case 47:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.InsertStmt{Into: yyDollar[3].str, Query: yyDollar[6].node}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.PingStmt{}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.SelectStmt{AttrList: yyDollar[2].node, Query: yyDollar[3].node}
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectVersionStmt{}
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: yyDollar[2].str}
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: yyDollar[2].str, In: yyDollar[5].str}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "fund", Name: yyDollar[3].str}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "project", Name: yyDollar[3].str}
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "projects"}
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "version"}
		}
	case 57:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: yyDollar[4].str, Value: yyDollar[6].str, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 58:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: yyDollar[4].str, ValueNull: true, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 59:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: "fund", Value: yyDollar[6].str, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 60:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: "fund", ValueNull: true, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: yyDollar[1].str}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "*"}
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "count(*)"}
		}
	case 64:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.QueryClause{From: yyDollar[2].str, Where: yyDollar[3].node, Order: yyDollar[4].node, Limit: yyDollar[5].node, Offset: yyDollar[6].node}
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{Valid: true, Condition: yyDollar[2].node}
		}
	case 66:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 68:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: true}
		}
	case 70:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{Valid: true, Count: yyDollar[2].str}
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{}
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{Valid: true, Start: yyDollar[2].str}
		}
	case 74:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{}
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.AndExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.NotExpr{Expr: yyDollar[2].node}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.EqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LikeExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ILikeExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.NotEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 93:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FilterExpr{Filter: yyDollar[3].str}
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.TagExpr{ExprList: yyDollar[3].nodeList}
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Name{Value: yyDollar[1].str}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Name{Value: "fund"}
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SLiteral{Value: ast.DecodeSLiteral(yyDollar[1].str)}
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Number{Value: yyDollar[1].str}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ParenExpr{Expr: yyDollar[2].node}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].nodeList...)
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{&ast.Name{Value: yyDollar[1].str}}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = strings.ToLower(yyDollar[1].str)
		}
	}
	goto yystack /* stack new state and value */
}
