// Code generated by goyacc -l -o gram.go gram.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"strings"

	"github.com/indexdata/ccms/cmd/ccd/ast"
)

type yySymType struct {
	yys      int
	node     ast.Node
	str      string
	nodeList []ast.Node
}

const GT_OR_EQUAL = 57346
const LT_OR_EQUAL = 57347
const NOT_EQUAL = 57348
const ADD = 57349
const ALL = 57350
const ALTER = 57351
const AND = 57352
const ARCHIVE = 57353
const ARCHIVED = 57354
const ASC = 57355
const BY = 57356
const CREATE = 57357
const COUNT = 57358
const DELETE = 57359
const DESC = 57360
const DROP = 57361
const ENCRYPTED = 57362
const FILTER = 57363
const FROM = 57364
const FUND = 57365
const ILIKE = 57366
const IN = 57367
const INFO = 57368
const INSERT = 57369
const INTO = 57370
const LIKE = 57371
const LIMIT = 57372
const NOT = 57373
const NULL = 57374
const OFFSET = 57375
const OR = 57376
const ORDER = 57377
const PASSWORD = 57378
const PROJECT = 57379
const PROJECTS = 57380
const PROPERTY = 57381
const PING = 57382
const RETRIEVE = 57383
const SELECT = 57384
const SET = 57385
const SHOW = 57386
const TAG = 57387
const TO = 57388
const UPDATE = 57389
const USER = 57390
const VERSION = 57391
const WHERE = 57392
const WITH = 57393
const IDENT = 57394
const NUMBER = 57395
const SLITERAL = 57396

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"GT_OR_EQUAL",
	"LT_OR_EQUAL",
	"NOT_EQUAL",
	"ADD",
	"ALL",
	"ALTER",
	"AND",
	"ARCHIVE",
	"ARCHIVED",
	"ASC",
	"BY",
	"CREATE",
	"COUNT",
	"DELETE",
	"DESC",
	"DROP",
	"ENCRYPTED",
	"FILTER",
	"FROM",
	"FUND",
	"ILIKE",
	"IN",
	"INFO",
	"INSERT",
	"INTO",
	"LIKE",
	"LIMIT",
	"NOT",
	"NULL",
	"OFFSET",
	"OR",
	"ORDER",
	"PASSWORD",
	"PROJECT",
	"PROJECTS",
	"PROPERTY",
	"PING",
	"RETRIEVE",
	"SELECT",
	"SET",
	"SHOW",
	"TAG",
	"TO",
	"UPDATE",
	"USER",
	"VERSION",
	"WHERE",
	"WITH",
	"IDENT",
	"NUMBER",
	"SLITERAL",
	"';'",
	"'*'",
	"'('",
	"')'",
	"'='",
	"'<'",
	"'>'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 221

var yyAct = [...]uint8{
	112, 164, 107, 103, 101, 88, 108, 104, 78, 136,
	135, 183, 118, 200, 199, 184, 198, 197, 123, 122,
	182, 166, 56, 120, 94, 138, 137, 81, 80, 95,
	57, 36, 178, 54, 58, 62, 167, 50, 64, 65,
	66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
	76, 110, 77, 113, 131, 53, 204, 110, 57, 113,
	83, 84, 55, 203, 202, 133, 134, 106, 57, 181,
	176, 201, 130, 194, 187, 111, 147, 129, 91, 98,
	93, 111, 57, 115, 114, 57, 97, 116, 57, 115,
	114, 59, 145, 116, 90, 174, 57, 121, 148, 119,
	124, 125, 173, 172, 171, 60, 61, 128, 57, 89,
	85, 92, 57, 57, 132, 100, 99, 150, 96, 39,
	57, 139, 37, 144, 146, 140, 4, 141, 143, 151,
	152, 154, 155, 156, 157, 153, 38, 126, 162, 165,
	158, 159, 160, 161, 46, 186, 47, 169, 51, 175,
	177, 179, 180, 149, 82, 79, 45, 117, 170, 25,
	48, 26, 40, 63, 41, 27, 49, 28, 127, 29,
	87, 188, 189, 190, 191, 192, 30, 31, 42, 86,
	1, 163, 195, 109, 43, 165, 193, 196, 105, 44,
	35, 102, 32, 185, 33, 168, 142, 34, 52, 23,
	22, 21, 20, 24, 19, 18, 17, 16, 15, 14,
	13, 12, 11, 10, 9, 8, 7, 6, 3, 5,
	2,
}

var yyPact = [...]int16{
	150, -1000, -1000, -24, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 99, 82, 141, 134, 123,
	-17, 120, 6, 68, 33, -1000, 150, 33, 33, 33,
	33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
	-1000, 33, 133, -29, -1000, -1000, -30, -1000, 129, 33,
	33, -1000, 67, -1000, 170, 161, -1000, 59, -1000, -1000,
	-1000, 43, 59, -1000, -1000, -1000, -1000, 69, -1000, 33,
	-34, -27, 81, -1000, -1000, 56, 77, 76, -1000, 36,
	137, -1000, -44, 59, -1000, -35, 33, -40, -41, 33,
	33, -1000, 103, 158, -1000, 48, 36, 5, -1000, -1000,
	-31, -32, -1000, -1000, -1000, -1000, 36, 89, 133, 93,
	-1000, -1000, 60, 44, 55, 110, 36, 36, 30, 30,
	30, 30, -1000, 30, 30, 30, 30, 33, 33, -37,
	-18, -1000, 117, 144, 54, 53, 52, 45, 16, -22,
	33, 61, 158, -1000, 5, 5, 5, 5, -1000, -1000,
	-1000, -1000, -38, -47, -1000, -1000, -1000, -1000, 112, 21,
	33, 33, 33, 33, 33, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 33, -1000, 20, -1000, 169, -42,
	-43, -45, -46, -1000, -1000, -1000, -1000, 18, 11, 10,
	3, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 220, 219, 126, 218, 217, 216, 215, 214, 213,
	212, 211, 210, 209, 208, 207, 206, 205, 204, 203,
	202, 201, 200, 199, 198, 8, 5, 196, 195, 193,
	4, 191, 3, 188, 2, 7, 6, 183, 181, 1,
	0, 180,
}

var yyR1 = [...]int8{
	0, 41, 1, 4, 4, 4, 3, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 7, 5, 5, 6,
	6, 6, 6, 6, 8, 9, 10, 11, 12, 13,
	14, 15, 16, 17, 18, 18, 20, 19, 21, 21,
	22, 22, 22, 22, 22, 23, 23, 23, 23, 24,
	24, 24, 25, 26, 26, 27, 27, 27, 27, 28,
	28, 29, 29, 30, 31, 31, 32, 32, 35, 35,
	33, 33, 33, 33, 33, 34, 34, 34, 34, 34,
	36, 36, 36, 37, 37, 37, 37, 37, 38, 38,
	39, 40,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 2, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 3, 8, 8, 8,
	8, 8, 8, 8, 4, 3, 3, 3, 7, 4,
	3, 3, 3, 3, 1, 2, 6, 1, 3, 4,
	2, 5, 3, 3, 2, 10, 10, 10, 10, 1,
	1, 4, 6, 2, 0, 3, 4, 4, 0, 2,
	0, 2, 0, 1, 1, 3, 1, 3, 1, 2,
	1, 3, 3, 3, 3, 1, 3, 3, 3, 3,
	1, 4, 4, 1, 1, 1, 1, 3, 1, 3,
	1, 1,
}

var yyChk = [...]int16{
	-1000, -41, -1, -4, -3, -2, -5, -6, -7, -8,
	-9, -10, -11, -12, -13, -14, -15, -16, -17, -18,
	-20, -21, -22, -23, -19, 9, 11, 15, 17, 19,
	26, 27, 42, 44, 47, 40, 55, 23, 37, 37,
	21, 23, 37, 43, 48, 22, 21, 23, 37, 43,
	54, 28, -24, 49, -40, 56, 16, 52, -40, 23,
	37, 38, -40, -3, -40, -40, -40, -40, -40, -40,
	-40, -40, -40, -40, -40, -40, -40, -40, -25, 22,
	57, 57, 25, -40, -40, 43, 9, 9, -26, 50,
	51, -26, 42, -40, 58, 56, 37, -40, 23, 39,
	39, -30, -31, -32, -35, -33, 31, -34, -36, -37,
	21, 45, -40, 23, 54, 53, 57, 20, 56, -26,
	58, -40, 59, 59, -40, -40, 34, 10, 59, 29,
	24, 6, -35, 60, 61, 5, 4, 57, 57, -30,
	36, -25, -27, 35, -40, 32, -40, 32, 43, 43,
	7, 19, -32, -35, -34, -34, -34, -34, -36, -36,
	-36, -36, -40, -38, -39, -40, 58, 54, -28, 30,
	14, 50, 50, 50, 50, -40, 54, -40, 54, -40,
	-40, 8, 58, 58, 62, -29, 33, 53, -40, -40,
	-40, -40, -40, -39, 53, 13, 18, 59, 59, 59,
	59, 53, 53, 53, 53,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 22, 23, 24, 25, 0, 0, 0, 0, 0,
	44, 0, 0, 0, 0, 47, 4, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	45, 0, 0, 0, 59, 60, 0, 101, 50, 0,
	0, 54, 0, 5, 0, 0, 26, 64, 35, 36,
	37, 0, 64, 40, 41, 42, 43, 0, 48, 0,
	0, 0, 0, 52, 53, 0, 0, 0, 34, 0,
	0, 39, 0, 64, 49, 0, 0, 0, 0, 0,
	0, 63, 73, 74, 76, 78, 0, 80, 85, 90,
	0, 0, 93, 94, 95, 96, 0, 0, 0, 68,
	61, 51, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 79, 0, 0, 0, 0, 0, 0, 0,
	0, 46, 70, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 75, 77, 81, 82, 83, 84, 86, 87,
	88, 89, 0, 0, 98, 100, 97, 38, 72, 0,
	0, 0, 0, 0, 0, 27, 28, 29, 30, 31,
	32, 33, 91, 92, 0, 62, 0, 69, 65, 0,
	0, 0, 0, 99, 71, 66, 67, 0, 0, 0,
	0, 55, 56, 57, 58,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	57, 58, 56, 3, 62, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 55,
	60, 59, 61,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.ParseTree{Commands: yyDollar[1].nodeList}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].nodeList...)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{yyDollar[1].node}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ArchiveProjectStmt{}
		}
	case 27:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterFundStmt{Fund: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: yyDollar[8].str, StringLiteral: false}
		}
	case 28:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterFundStmt{Fund: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: ast.DecodeSLiteral(yyDollar[8].str), StringLiteral: true}
		}
	case 29:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: yyDollar[8].str, StringLiteral: false}
		}
	case 30:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: ast.DecodeSLiteral(yyDollar[8].str), StringLiteral: true}
		}
	case 31:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Add, Value: yyDollar[8].str}
		}
	case 32:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Drop, Value: yyDollar[8].str}
		}
	case 33:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Drop, Value: "*"}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CreateFilterStmt{Filter: yyDollar[3].str, Where: yyDollar[4].node}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateFundStmt{Fund: yyDollar[3].str}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateProjectStmt{Project: yyDollar[3].str}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateSetStmt{Set: yyDollar[3].str}
		}
	case 38:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.CreateUserStmt{User: yyDollar[3].str, EncryptedPassword: ast.DecodeSLiteral(yyDollar[7].str)}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DeleteStmt{From: yyDollar[3].str, Where: yyDollar[4].node}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropFilterStmt{Filter: yyDollar[3].str}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropFundStmt{Fund: yyDollar[3].str}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropProjectStmt{Project: yyDollar[3].str}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropSetStmt{Set: yyDollar[3].str}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: ""}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: ast.DecodeSLiteral(yyDollar[2].str)}
		}
	case 46:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.InsertStmt{Into: yyDollar[3].str, Query: yyDollar[6].node}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.PingStmt{}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.SelectStmt{AttrList: yyDollar[2].node, Query: yyDollar[3].node}
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectVersionStmt{}
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: yyDollar[2].str}
		}
	case 51:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: yyDollar[2].str, In: yyDollar[5].str}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "fund", Name: yyDollar[3].str}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "project", Name: yyDollar[3].str}
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "projects"}
		}
	case 55:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: yyDollar[4].str, Value: yyDollar[6].str, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 56:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: yyDollar[4].str, ValueNull: true, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 57:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: "fund", Value: yyDollar[6].str, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 58:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: "fund", ValueNull: true, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: yyDollar[1].str}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "*"}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "count(*)"}
		}
	case 62:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.QueryClause{From: yyDollar[2].str, Where: yyDollar[3].node, Order: yyDollar[4].node, Limit: yyDollar[5].node, Offset: yyDollar[6].node}
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{Valid: true, Condition: yyDollar[2].node}
		}
	case 64:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: true}
		}
	case 68:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{}
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{Valid: true, Count: yyDollar[2].str}
		}
	case 70:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{Valid: true, Start: yyDollar[2].str}
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{}
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.AndExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.NotExpr{Expr: yyDollar[2].node}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.EqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LikeExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ILikeExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.NotEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 91:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FilterExpr{Filter: yyDollar[3].str}
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.TagExpr{ExprList: yyDollar[3].nodeList}
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Name{Value: yyDollar[1].str}
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Name{Value: "fund"}
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SLiteral{Value: ast.DecodeSLiteral(yyDollar[1].str)}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Number{Value: yyDollar[1].str}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ParenExpr{Expr: yyDollar[2].node}
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].nodeList...)
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{&ast.Name{Value: yyDollar[1].str}}
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = strings.ToLower(yyDollar[1].str)
		}
	}
	goto yystack /* stack new state and value */
}
