==== select

Retrieve data

[source,subs="verbatim,quotes"]
----
select { * | count(*) }
    from `**_set_name_**`
    [ where `**_search_condition_**` ]
    [ order by `**_attribute_**` [ asc | desc ] ]
    [ limit `**_count_**` ]
    [ offset `**_start_**` ]
----

[discrete]
===== Description

The `select` command retrieves data, typically a list of objects from
a set according to specified criteria.

NOTE:  The CCMS server returns to the client no more than 10000
records per `select` command.  If a result set is larger than this,
the server returns an error.  It is a good idea to use a `limit`
clause if the query may return a large result set.

[discrete]
===== Parameters

The first argument specifies `\*` meaning all available attributes or
`count(*)` meaning a count of the number of rows returned.

[discrete]
====== from

The `from` clause specifies the desired set that will be the source of
data.

[discrete]
====== where

The `where` clause specifies a search condition in the form of a
Boolean expression.  Only objects that satisfy this condition will be
retrieved.

See also *Reference > Queries*.

[discrete]
====== order by

The `order by` clause specifies a sort order for objects to be
returned.  The objects are sorted by the specified `*_attribute_*`,
with `asc` for ascending order (the default) or `desc` for descending
order.

[discrete]
====== limit

The `limit` clause specifies the maximum number of objects that will
be returned.

[discrete]
====== offset

The `offset` clause specifies a number of objects that will be skipped
and not returned as part of the result.  This can be useful for
retrieving objects one page of data at a time.  Note that the `order
by` clause is required when `offset` is used.

[discrete]
===== Examples

To retrieve items in stock from the set `test.myset`:

----
select * from test.myset where availability = 'In stock' order by title;
----

